// Copyright (c) 2026, osama.ahmed@deliverydevs.com and contributors
// For license information, please see license.txt

frappe.ui.form.on("Coupon Entry", {
	setup(frm) {
		frm.set_query("book", () => ({
			query: "donation_management.donation_management.doctype.coupon_entry.coupon_entry.get_available_books",
		}));
		frm.set_query("book_serial_no", () => ({
			query: "donation_management.donation_management.doctype.coupon_entry.coupon_entry.get_available_coupon_serials",
			filters: { book: frm.doc.book },
		}));
	},

	refresh(frm) {
		if (frm.doc.book) {
			set_coupon_book_details(frm);
		}
		if (frm.doc.docstatus === 1) {
			frappe.call({
				method: "donation_management.donation_management.doctype.coupon_entry.coupon_entry.sync_coupon_entry_leaf_connections",
				args: { coupon_entry: frm.doc.name },
				callback(response) {
					if (response.message) {
						frm.dashboard.refresh();
					}
				},
			});
		}
	},

	on_submit(frm) {
		// Coupon Book Leafs are generated by the server during submission.
		// Refresh Connections after that transaction so their count is visible immediately.
		frm.dashboard.refresh();
	},

	book(frm) {
		set_coupon_book_details(frm);
	},

	book_serial_no(frm) {
		if (frm.doc.book) {
			set_coupon_book_details(frm);
		}
	},

	number_of_pages(frm) {
		set_coupon_amount(frm);
	},
});

function set_coupon_book_details(frm) {
	if (!frm.doc.book) {
		return;
	}

	const request_id = (frm.__coupon_details_request_id || 0) + 1;
	frm.__coupon_details_request_id = request_id;
	const requested_book = frm.doc.book;
	const requested_book_serial_no = frm.doc.book_serial_no;

	frappe.call({
		method: "donation_management.donation_management.doctype.coupon_entry.coupon_entry.get_coupon_book_details",
		args: {
			book: frm.doc.book,
			book_serial_no: frm.doc.book_serial_no,
		},
		callback(response) {
			if (
				request_id !== frm.__coupon_details_request_id
				|| frm.doc.book !== requested_book
				|| frm.doc.book_serial_no !== requested_book_serial_no
			) {
				return;
			}

			const book = response.message || {};
			if (book.requires_book_serial_no && !frm.doc.book_serial_no) {
				frm.toggle_reqd("book_serial_no", true);
				frm.__coupon_value = 0;
				set_derived_value(frm, "coupon_color", "");
				set_derived_value(frm, "volunteer_name", "");
				set_derived_value(frm, "area", "");
				set_derived_value(frm, "warehouse", "");
				return;
			}
			frm.toggle_reqd("book_serial_no", false);

			if (frm.is_new() && (book.book_type !== "Coupon Book" && book.book_type !== "Mixed" || book.status !== "Issued" || cint(book.remaining_pages) <= 0)) {
				frappe.msgprint({
					title: __("All Pages Used"),
					message: __("Book {0} is not an issued Coupon Book with available pages.", [
						frm.doc.book,
					]),
					indicator: "red",
				});
				frm.set_value("book", "");
				set_derived_value(frm, "coupon_color", "");
				set_derived_value(frm, "volunteer_name", "");
				set_derived_value(frm, "area", "");
				set_derived_value(frm, "warehouse", "");
				return;
			}

			set_derived_value(frm, "coupon_color", book.coupon_color || "");
			set_derived_value(frm, "volunteer_name", book.volunteer_name || "");
			set_derived_value(frm, "area", book.volunteer_area || "");
			set_derived_value(frm, "warehouse", book.warehouse || "");
			frm.__coupon_value = cint(book.coupon_value);
			if (!cint(frm.doc.number_of_pages)) {
				set_derived_value(frm, "number_of_pages", 1);
			}
			set_coupon_amount(frm);
		},
	});
}

function set_coupon_amount(frm) {
	const coupon_value = cint(frm.__coupon_value);
	if (!coupon_value) {
		return;
	}

	set_derived_value(frm, "amount", cint(frm.doc.number_of_pages) * coupon_value);
}

function set_derived_value(frm, fieldname, value) {
	return frm.set_value(fieldname, value, null, true);
}
